

# configmap-t13s.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: serverpod-config-t13s
data:
  # --- Настройки базы данных для t13s ---
  SERVERPOD_DATABASE_HOST: "192.168.0.6"
  SERVERPOD_DATABASE_PORT: "5432"
  SERVERPOD_DATABASE_NAME: "t13s_db"
  SERVERPOD_DATABASE_USER: "t13s_user"
  SERVERPOD_DATABASE_REQUIRE_SSL: "true"

  SERVERPOD_API_SERVER_PORT: "8080"
  SERVERPOD_INSIGHTS_SERVER_PORT: "8081" 
  SERVERPOD_WEB_SERVER_PORT: "8082"

  SERVERPOD_REDIS_ENABLED: "true"
  SERVERPOD_REDIS_HOST: "192.168.0.7"
  SERVERPOD_REDIS_PORT: "6379"
  SERVERPOD_REDIS_USER: "default"

  SERVERPOD_API_SERVER_PUBLIC_HOST: "api5.my-points.ru"
  SERVERPOD_API_SERVER_PUBLIC_PORT: "443"
  SERVERPOD_API_SERVER_PUBLIC_SCHEME: "https"

  SERVERPOD_WEB_SERVER_PUBLIC_HOST: "web5.my-points.ru"
  SERVERPOD_WEB_SERVER_PUBLIC_PORT: "443"
  SERVERPOD_WEB_SERVER_PUBLIC_SCHEME: "https"

  SERVERPOD_INSIGHTS_SERVER_PUBLIC_HOST: "insights5.my-points.ru"
  SERVERPOD_INSIGHTS_SERVER_PUBLIC_PORT: "443"
  SERVERPOD_INSIGHTS_SERVER_PUBLIC_SCHEME: "https"

  # --- Общие настройки ---
  SERVERPOD_MAX_REQUEST_SIZE: "524288"
  SERVERPOD_LOGGING_MODE: "production"

    